services:
  postgres:
    image: postgres:16
    container_name: sge-postgres
    environment:
      POSTGRES_USER: sge
      POSTGRES_PASSWORD: sge
      POSTGRES_DB: sge
    networks:
      - sge-net
    restart: always

  backend:
    build: ./backend
    container_name: sge-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    environment:
      - DATABASE_URL=postgresql://sge:sge@postgres:5432/sge
      - POSTGRES_USER=sge
      - POSTGRES_PASSWORD=sge
      - POSTGRES_DB=sge
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - JWT_SECRET_KEY=sgesecretkey18
    depends_on:
      - postgres
    networks:
      - sge-net
    restart: always

  caddy:
    image: caddy:latest
    container_name: sge-caddy
    restart: always
    ports:
      - "3003:80"
      - "3004:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - sge-net

networks:
  sge-net:
    driver: bridge
