services:
  postgres:
    image: postgres:16
    container_name: sge-postgres
    environment:
      POSTGRES_USER: sge
      POSTGRES_PASSWORD: sge
      POSTGRES_DB: sge
    networks:
      - sge-net
    restart: always

  backend:
    build: ./backend
    container_name: sge-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --proxy-headers
    ports:
      - "8001:8001"
    environment:
      - .env
    depends_on:
      - postgres
    networks:
      - sge-net
    restart: always

  caddy:
    image: caddy:latest
    container_name: sge-caddy
    restart: always
    ports:
      - "3003:80"
      #- "3004:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend:/srv/apps/sge/frontend
    networks:
      - sge-net

networks:
  sge-net:
    driver: bridge
