services:
  app:
    build: .
    env_file:
      - .env.local
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "8000:8000" # Pastikan kamu membuka port agar bisa akses dari browser
