"""kategori dan satuan jadi master table, material pakai FK

Revision ID: 04ee08dc74bb
Revises: 829bc7e28c37
Create Date: 2026-06-28 20:47:21.495444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ee08dc74bb'
down_revision: Union[str, None] = '829bc7e28c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kategori', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_kategori')
    )
    op.create_index(op.f('ix_kategori_id'), 'kategori', ['id'], unique=False)
    op.create_table('satuan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_satuan', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_satuan')
    )
    op.create_index(op.f('ix_satuan_id'), 'satuan', ['id'], unique=False)
    # --- TAMBAHAN MANUAL: seed data dulu, sebelum dipakai buat backfill ---
    op.execute("""
        INSERT INTO kategori (nama_kategori) VALUES
        ('kabel'), ('housing'), ('terminal'), ('lainnya')
    """)
    op.execute("""
        INSERT INTO satuan (nama_satuan) VALUES ('m'), ('pcs')
    """)

    # --- DIUBAH: nullable=True dulu, biar bisa backfill 651 baris lama ---
    op.add_column('material', sa.Column('satuan_id', sa.Integer(), nullable=True))
    op.add_column('material', sa.Column('kategori_id', sa.Integer(), nullable=True))

    # --- TAMBAHAN MANUAL: backfill, cocokin value string lama ke id baru ---
    op.execute("""
        UPDATE material
        SET kategori_id = (SELECT id FROM kategori WHERE kategori.nama_kategori = material.kategori)
    """)
    op.execute("""
        UPDATE material
        SET satuan_id = (SELECT id FROM satuan WHERE satuan.nama_satuan = material.satuan_terkecil)
    """)

    op.create_foreign_key(None, 'material', 'satuan', ['satuan_id'], ['id'])
    op.create_foreign_key(None, 'material', 'kategori', ['kategori_id'], ['id'])
    op.drop_column('material', 'kategori')
    op.drop_column('material', 'satuan_terkecil')

    # --- TAMBAHAN MANUAL: sekarang semua baris udah keisi, baru wajibin NOT NULL ---
    op.alter_column('material', 'satuan_id', nullable=False)
    op.alter_column('material', 'kategori_id', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('satuan_terkecil', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('material', sa.Column('kategori', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'material', type_='foreignkey')
    op.drop_constraint(None, 'material', type_='foreignkey')
    op.drop_column('material', 'kategori_id')
    op.drop_column('material', 'satuan_id')
    op.drop_index(op.f('ix_satuan_id'), table_name='satuan')
    op.drop_table('satuan')
    op.drop_index(op.f('ix_kategori_id'), table_name='kategori')
    op.drop_table('kategori')
    # ### end Alembic commands ###
