"""create supplier table

Revision ID: 1af723983c10
Revises: 4d7703b993eb
Create Date: 2026-06-20 17:58:08.871170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af723983c10'
down_revision: Union[str, None] = '4d7703b993eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_sup', sa.String(length=50), nullable=False),
    sa.Column('nama_sup', sa.String(length=255), nullable=False),
    sa.Column('tipe', sa.String(length=10), nullable=False),
    sa.Column('direktur', sa.String(length=100), nullable=True),
    sa.Column('contact_person_1', sa.String(length=100), nullable=True),
    sa.Column('contact_person_2', sa.String(length=100), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('no_telp_1', sa.String(length=30), nullable=True),
    sa.Column('no_telp_2', sa.String(length=30), nullable=True),
    sa.Column('no_hp_1', sa.String(length=30), nullable=True),
    sa.Column('no_hp_2', sa.String(length=30), nullable=True),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.Column('material_dapat_disupply', sa.Text(), nullable=True),
    sa.Column('lead_time_delivery', sa.Integer(), nullable=True),
    sa.Column('lead_time_produksi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_id'), 'supplier', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_kode_sup'), 'supplier', ['kode_sup'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_kode_sup'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_id'), table_name='supplier')
    op.drop_table('supplier')
    # ### end Alembic commands ###
