"""create material table

Revision ID: 3ff7b6bb69fe
Revises: 61ca60666a39
Create Date: 2026-06-21 14:17:27.762704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff7b6bb69fe'
down_revision: Union[str, None] = '61ca60666a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_material', sa.String(length=255), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('satuan_terkecil', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_id'), 'material', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_id'), table_name='material')
    op.drop_table('material')
    # ### end Alembic commands ###
