"""create customer table

Revision ID: 4d7703b993eb
Revises: 
Create Date: 2026-06-20 16:00:23.393590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7703b993eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_cust', sa.String(length=50), nullable=False),
    sa.Column('nama_cust', sa.String(length=255), nullable=False),
    sa.Column('contact_person_1', sa.String(length=100), nullable=True),
    sa.Column('contact_person_2', sa.String(length=100), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('no_telp_1', sa.String(length=30), nullable=True),
    sa.Column('no_telp_2', sa.String(length=30), nullable=True),
    sa.Column('no_hp_1', sa.String(length=30), nullable=True),
    sa.Column('no_hp_2', sa.String(length=30), nullable=True),
    sa.Column('email_1', sa.String(length=100), nullable=True),
    sa.Column('email_2', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_index(op.f('ix_customer_kode_cust'), 'customer', ['kode_cust'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_kode_cust'), table_name='customer')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
