"""create jasa table

Revision ID: 61ca60666a39
Revises: 1af723983c10
Create Date: 2026-06-21 14:04:52.479534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ca60666a39'
down_revision: Union[str, None] = '1af723983c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jasa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jenis_pekerjaan', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jasa_id'), 'jasa', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jasa_id'), table_name='jasa')
    op.drop_table('jasa')
    # ### end Alembic commands ###
