"""drop supplier_kategori, kategori dari material

Revision ID: 829bc7e28c37
Revises: d71efe9ce68a
Create Date: 2026-06-27 14:10:14.018941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829bc7e28c37'
down_revision: Union[str, None] = 'd71efe9ce68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_kategori_id', table_name='supplier_kategori')
    op.drop_table('supplier_kategori')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_kategori',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kategori', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='supplier_kategori_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='supplier_kategori_pkey')
    )
    op.create_index('ix_supplier_kategori_id', 'supplier_kategori', ['id'], unique=False)
    # ### end Alembic commands ###
