"""create bom table

Revision ID: b0973075fd29
Revises: da1de47f9fb0
Create Date: 2026-06-22 11:34:17.192262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0973075fd29'
down_revision: Union[str, None] = 'da1de47f9fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_barang_customer_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('penggunaan', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['kode_barang_customer_id'], ['kode_barang_customer.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_id'), 'bom', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bom_id'), table_name='bom')
    op.drop_table('bom')
    # ### end Alembic commands ###
