"""kategori supplier multi-select, material simpan kategori sendiri

Revision ID: d71efe9ce68a
Revises: a97ed4ea4cb6
Create Date: 2026-06-27 13:36:41.912057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71efe9ce68a'
down_revision: Union[str, None] = 'a97ed4ea4cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_kategori_id'), 'supplier_kategori', ['id'], unique=False)

    # --- TAMBAHAN MANUAL: pindahin data kategori lama sebelum kolomnya dihapus ---
    op.execute("""
        INSERT INTO supplier_kategori (supplier_id, kategori)
        SELECT id, kategori FROM supplier WHERE kategori IS NOT NULL
    """)

    # --- DIUBAH: tambahin server_default biar 651 baris lama otomatis keisi 'lainnya' ---
    op.add_column('material', sa.Column('kategori', sa.String(length=20), nullable=False, server_default='lainnya'))
    op.alter_column('material', 'kategori', server_default=None)

    op.drop_column('supplier', 'kategori')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('kategori', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('material', 'kategori')
    op.drop_index(op.f('ix_supplier_kategori_id'), table_name='supplier_kategori')
    op.drop_table('supplier_kategori')
    # ### end Alembic commands ###
