"""create kode_barang_customer table

Revision ID: da1de47f9fb0
Revises: 3ff7b6bb69fe
Create Date: 2026-06-21 14:23:50.029314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1de47f9fb0'
down_revision: Union[str, None] = '3ff7b6bb69fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kode_barang_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_barang', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kode_barang_customer_id'), 'kode_barang_customer', ['id'], unique=False)
    op.create_index(op.f('ix_kode_barang_customer_kode_barang'), 'kode_barang_customer', ['kode_barang'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kode_barang_customer_kode_barang'), table_name='kode_barang_customer')
    op.drop_index(op.f('ix_kode_barang_customer_id'), table_name='kode_barang_customer')
    op.drop_table('kode_barang_customer')
    # ### end Alembic commands ###
