"""tambah urutan ke jasa, unique constraint jenis_pekerjaan

Revision ID: f1253e66ab9e
Revises: 04ee08dc74bb
Create Date: 2026-06-29 10:48:57.094260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1253e66ab9e'
down_revision: Union[str, None] = '04ee08dc74bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jasa', sa.Column('urutan', sa.Integer(), nullable=True))
    op.alter_column('jasa', 'jenis_pekerjaan',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'jasa', ['jenis_pekerjaan'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jasa', type_='unique')
    op.alter_column('jasa', 'jenis_pekerjaan',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('jasa', 'urutan')
    # ### end Alembic commands ###
