"""create barang_jasa table

Revision ID: f904a0f28bb1
Revises: b0973075fd29
Create Date: 2026-06-22 11:43:16.662389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f904a0f28bb1'
down_revision: Union[str, None] = 'b0973075fd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang_jasa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_barang_customer_id', sa.Integer(), nullable=False),
    sa.Column('jasa_id', sa.Integer(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jasa_id'], ['jasa.id'], ),
    sa.ForeignKeyConstraint(['kode_barang_customer_id'], ['kode_barang_customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barang_jasa_id'), 'barang_jasa', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barang_jasa_id'), table_name='barang_jasa')
    op.drop_table('barang_jasa')
    # ### end Alembic commands ###
